# SAMPLE-DATA SMOKE TEST - same 5-day feature sweep as smoke_test.conf but
# running entirely on the synthetic corpus in resources_sample/ (no licensed
# data required). Regenerate the corpus with:  python3 generate_sample_data.py
# Run with:  ./gradlew run -Pconf=scenarios/sample_smoke.conf

[agents]
max_siblings = 0
percent_single_parents = 100.0
age_start = 3
age_finish = 3
days_per_year = 5

[environment.locations]
utterances = "./resources_sample/utterances"
books = "./resources_sample/books"

[[ses]]
name = "Welfare"
qty = 8767

[[ses]]
name = "Working"
qty = 17514

[[ses]]
name = "Professional"
qty = 30142

[[child_profile]]
name = "typical"
count = 2

[[child_profile]]
name = "inattentive"
count = 2
attentiveness = 0.5

[[utterance_pool]]
name = "esl_demo"
path = "./resources_sample/utterances_esl"

[[parent_profile]]
name = "standard"
pool = "default"

[[parent_profile]]
name = "esl_demo"
pool = "esl_demo"
daily_words_factor = 0.9

[[home_profile]]
name = "no_books"
books_per_day = 0

[[home_profile]]
name = "two_books"
books_per_day = 2
