# SAMPLE-DATA DEMO YEAR - a full one-year run (3 children, one per SES tier)
# on the synthetic corpus in resources_sample/. Works on a fresh clone with
# no licensed data. Takes roughly 8-10 minutes.
# NOTE: results demonstrate the machinery only - the synthetic corpus does
# NOT reproduce the CPB-LEX paper's Table 6 numbers; the real corpus is
# required for research conclusions.
# Run with:  ./gradlew run -Pconf=scenarios/sample_year.conf

[agents]
child = 3
max_siblings = 0
percent_single_parents = 100.0
age_start = 3
age_finish = 3

[environment.locations]
utterances = "./resources_sample/utterances"
books = "./resources_sample/books"

[[ses]]
name = "Welfare"
qty = 8767

[[ses]]
name = "Working"
qty = 17514

[[ses]]
name = "Professional"
qty = 30142
