# Child Vocabulary Acquisition Simulation Configuration file
#
# Lines beginning with '#' are comments and are ignored by the parser.
# 
# Refer to https://toml.io for full details of the syntax.
#
# Omiting (by commenting out or removing) any keys will result in default
# values being used.
# Where a range of permitted values is given, the range is inclusive at both
# ends, and values outside of those ranges will be clamped to the nearest valid
# value.
#   e.g. setting 'max_siblings' to '-1' will be treated as if a '0' was
#        entered, while a value of '30' will be treated as if a '2' had been.

# Start of agent-related configuration
[agents]

# Number of child agents to generate in the simulation
# WARNING: Be sensible here, as you may run out of RAM if you have too many.
# Consider running the simulation multiple times with only hundreds of agents
# rather than trying to run it once with thousands.
# child = 10

# Max number of siblings per child agent
# Valid range: 0 - 2
# max_siblings = 0

# Percentage of homes which are single parent households.
# Valid range: 0.0 - 100.0.
# Values outside are clamped to nearest extreme (e.g. 150.5 becomes 100.0)
# percent_single_parents = 0.0

# Starting age of child agents, in whole years ('3.4' is not valid)
# Range: 0 (inclusive) - 5 (inclusive)
# age_start = 3

# Finishing age of child agents, in whole years ('6.4' is not valid)
# Range: 5 (inclusive) - 10 (inclusive)
# NOTE: If both starting & finishing ages are '5', finishing age will be
#       treated as if it were '6' instead.
# age_finish = 8

# Start of Socio-Economic Statuses (SES) configuration

# List of SES, and avg. daily number of words
# uttered by parents to their children (See REF. below).
# The child agents & their households will be distributed as evenly as possible
# across all listed SES.
# Therefore, it is highly recommended to make the number of child agents a
# multiple of the number SES defined here.
#
# NOTE: Duplicate category names will result in only one of those entries
#       being used while the rest will be ignored.
#
# REF: Green, C., Keogh, K., Sun, H., & O’Brien, B. (2024). "The Children’s 
#       Picture Books Lexicon (CPB-LEX): A large-scale lexical database from
#       children’s picture books". Behavior Research Methods, 56(5), 4504-4521.
#
#
# Each entry in this section MUST consists of 3 lines.
#       The first line MUST be '[[ses]]' (without the quotes).
#       The next two MUST contain the SES category name and quantity of words,
#       using the keys 'name' and 'qty' respectively.
#       Failing to do so will cause that entry to be ignored.
#
# The below 9 lines represent the default 3 categories which will be used if
# none are explicitly defined here.
#
# [[ses]]
# name="Welfare"
# qty=8767

# [[ses]]
# name="Working"
# qty=17514

# [[ses]]
# name="Professional"
# qty=30142

# Environment configuration
[environment.locations]
# Directory paths are case-sensitive if the underlying filesystem is.
# Per https://learn.microsoft.com/en-us/windows/wsl/case-sensitivity, 
# Windows 10, build 17107, and later supports configuring individual
# directories () to be case-sensitive

# Location where the collection of 'utterance' files are.
# Expected file-naming convention is that the actual utterances are in files
# which include 'utterance' in their name and have a file-extension of '.csv',
# while the participant metadata files have 'participants' in their name and
# the same '.csv' file-extension.
# utterances = "./resources/utterances"

# Location where the collection of 'book' files are.
# Files are expected to be UTF-8 encoded '.txt' files.
# books = "./resources/books"