[agents]
child = 3
max_siblings = 0
percent_single_parents = 100.0
age_start = 3
age_finish = 5

[environment.locations]
utterances = "./resources/utterances"
books = "./resources/books"

[[ses]]
name="Welfare"
qty=8767

[[ses]]
name="Working"
qty=17514

[[ses]]
name="Professional"
qty=30142